name: Manual Build v0.0.0.35

on: 
  workflow_dispatch: # 允許手動點擊執行

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
        DALAMUD_HOME: /tmp/dalamud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: 'v0.0.0.35' # 指定編譯這個版本
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v4 # 升級到 v4 比較穩
        with:
          dotnet-version: '10.0.x' 
          
      - name: Download Dalamud Latest
        run: |
          mkdir -p ${{ env.DALAMUD_HOME }}
          wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore Project
        run: dotnet restore

      - name: Build Project
        run: |
          # 使用原作者的路徑設定，並指定輸出 dll
          dotnet build --configuration Release WaymarkStudio/WaymarkStudio.csproj -p:DalamudLibPath=${{ env.DALAMUD_HOME }}

      - name: Upload Finished Plugin
        uses: actions/upload-artifact@v4
        with:
          name: WaymarkStudio-v0.0.0.35
          # 這裡抓取編譯出來的所有重要檔案
          path: |
            WaymarkStudio/bin/Release/WaymarkStudio/
